name: mazadi
description: A project for auctions.

version: 0.0.9+14

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  animations: ^2.0.7
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_config: ^2.0.0
  easy_localization: ^3.0.1
  get: ^4.6.6
  upgrader: ^10.3.0
  package_info_plus: ^4.0.2
  overlay_support: ^2.1.0
  flutter_svg_provider: ^1.0.3
  flutter_svg: ^2.0.9
  flutter_scale_tap: ^1.0.5
  flutter_spinkit: ^5.1.0
  easy_debounce: ^2.0.3
  google_fonts: ^4.0.3
  carousel_slider_plus: ^7.0.0
  dio: ^5.6.0
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.0.5
  flash: ^3.1.0
  email_validator: ^3.0.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.10
  cached_network_image: ^3.2.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  photo_manager: ^3.2.0
  dropdown_button2: ^2.3.9
  firebase_core: ^3.9.0
  firebase_analytics: ^11.3.6
  firebase_auth: ^5.3.4
  google_maps_flutter: ^2.2.7
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  uuid: ^4.4.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.0.15
  socket_io_client: ^2.0.3+1
  firebase_messaging: ^15.1.6
  infinite_scroll_pagination: ^4.0.0
  shimmer: ^3.0.0
  geolocator: ^12.0.0
  geolocator_android: 4.5.5
  flutter_typeahead: ^5.2.0
  flutter_google_places: ^0.3.0
  geocoding: ^3.0.0
  custom_info_window: ^1.0.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  masonry_grid: ^1.0.0
  readmore: ^3.0.0
  flutter_layout_grid: ^2.0.1
  flutter_staggered_grid_view: ^0.7.0
  debounce_throttle: ^2.0.0
  diacritic: ^0.1.3
  extended_sliver: ^2.1.3
  flutter_rating_bar: ^4.0.1
  emoji_picker_flutter: ^3.0.0
  enum_to_string: ^2.0.1
  flutter_keyboard_visibility: ^6.0.0
  animated_bottom_navigation_bar: ^1.3.3
  purchases_flutter: ^7.0.2
  google_mobile_ads: ^5.2.0
  flutter_linkify: ^6.0.0
  any_link_preview: ^3.0.0
  flutter_langdetect: ^0.0.2

flutter_native_splash:
  color: '#EE6148'
  image: assets/splash.png
  android_12:
    color: '#EE6148'
    image: 'assets/android12.png'

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/app-logo/1024.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - lib/lang/
    - assets/maps/
    - assets/jpg/
    - assets/splashscreen/
    - assets/icons/notifications/
    - assets/icons/social/
    - assets/icons/svg/
    - assets/icons/svg/intro/
    - assets/icons/svg/flags/
    - assets/icons/svg/profile/
    - assets/icons/categories/
