// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpb_5a6g4Mj1ifN_k7d49LIXpHAkxglDI',
    appId: '1:330115361812:web:82ea116ea9c5275a1e8b01',
    messagingSenderId: '330115361812',
    projectId: 'mazadi-c37c3',
    authDomain: 'mazadi-c37c3.firebaseapp.com',
    storageBucket: 'mazadi-c37c3.appspot.com',
    measurementId: 'G-GWZYS1W3EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkqn3tjPm4daq2roA5gxd2AiVefEr2NNI',
    appId: '1:741133992950:android:346e9c55925b8eb224fdd7',
    messagingSenderId: '741133992950',
    projectId: 'mazadi-omn',
    storageBucket: 'mazadi-omn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLmGeWJoDQbFTieAbrS9e7r6RuKxxNMFU',
    appId: '1:330115361812:ios:238b9d201452f47c1e8b01',
    messagingSenderId: '330115361812',
    projectId: 'mazadi-c37c3',
    storageBucket: 'mazadi-c37c3.appspot.com',
    androidClientId:
        '330115361812-q0fuc0gaemk7aosb0vki7053enadd203.apps.googleusercontent.com',
    iosClientId:
        '330115361812-rin1krq2kssc0748ulgo585hb15agr1n.apps.googleusercontent.com',
    iosBundleId: 'com.mazadiauction.name',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLmGeWJoDQbFTieAbrS9e7r6RuKxxNMFU',
    appId: '1:330115361812:ios:30e1e36c4f9d97331e8b01',
    messagingSenderId: '330115361812',
    projectId: 'mazadi-c37c3',
    storageBucket: 'mazadi-c37c3.appspot.com',
    androidClientId:
        '330115361812-q0fuc0gaemk7aosb0vki7053enadd203.apps.googleusercontent.com',
    iosClientId:
        '330115361812-e08gsut6r3fepjt2qdii2oom66nf10i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mazadiClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpb_5a6g4Mj1ifN_k7d49LIXpHAkxglDI',
    appId: '1:330115361812:web:fd1fe45e9ffba1f81e8b01',
    messagingSenderId: '330115361812',
    projectId: 'mazadi-c37c3',
    authDomain: 'mazadi-c37c3.firebaseapp.com',
    storageBucket: 'mazadi-c37c3.appspot.com',
    measurementId: 'G-WPN0CN7P5L',
  );
}